services:
  apix:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monitor_apix
    restart: always

    networks:
      - pi_default

    ports:
      - "8123:8000"

    healthcheck:
      # O healthcheck roda DENTRO do container.
      # Portanto deve chamar localhost:8000 (e N√ÉO 8123).
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  pi_default:
    external: true
