services:
  apix:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monitor_apix
    restart: always

    networks:
      - pi_default

    ports:
      - "8123:8000"

networks:
  pi_default:
    external: true
